import "@/styles/globals.css";

import { type Metadata } from "next";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={geist.className}>
                    <header className="flex justify-between items-center px-6 py-4 shadow-md border-b border-gray-200 bg-white">
                        <h1 className="text-xl font-semibold">Finverse</h1>
                        <div>
                            <SignedOut>
                                <SignInButton>
                                    <button className="bg-black text-white font-medium px-4 py-2 rounded-lg hover:bg-gray-900 transition">
                                        Sign In
                                    </button>
                                </SignInButton>
                            </SignedOut>
                            <SignedIn>
                                <UserButton />
                            </SignedIn>
                        </div>
                    </header>
                    <main className="p-6">{children}</main>
                </body>
            </html>
        </ClerkProvider>
    );
}
