name: Lint | Build | Deploy to Production

on:
    push:
        branches:
            - main

env:
    NODE_LTS_VERSION: 18
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
    lint_build:
        name: Lint and Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node v${{ env.NODE_LTS_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_LTS_VERSION }}
                  cache: "npm"
                  check-latest: true

            # - name: Cache dependencies and build outputs
            #   uses: actions/cache@v4
            #   with:
            #     path: |
            #       ~/.npm
            #       ${{ github.workspace }}/.next/cache
            #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
            #     restore-keys: |
            #       ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Install Dependencies
              run: |
                  echo "Installing Dependencies..."
                  npm ci --force

            - name: Pull Vercel Environment Information
              run: |
                  npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project
              run: |
                  echo "Building..."
                  npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project to Production
              run: |
                  echo "🎉 Deploying..."
                  npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --no-wait
